name: smartstock_pro
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animations: ^2.0.7
  bottom_navy_bar: ^6.0.0
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.14.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.1
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.0.4
  flutter_stripe: ^10.0.0
  http: ^1.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/bg_image.svg
    - assets/images/logo_icon.svg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/smartstockpro.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21
